on: [push, pull_request]
name: Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
