on:
  push:
    branches:
      - '*'
    paths:
      - 'src/*.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
  
name: Tests

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
      - name: Run clippy
        uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets

